services:
  - type: web
    name: bfhl-api
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_FULL_NAME
        value: harsha
      - key: APP_DOB
        value: 24012005
      - key: APP_EMAIL
        value: vermaharsha314@gmail.com
      - key: APP_ROLL_NUMBER
        value: 2311981227
      - key: PORT
        value: 8080
